feat: implement pull request if ci check passed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,6 +80,39 @@ jobs:
           path: bin/
           retention-days: 7
 
+  open_pull_request:
+    if: github.ref != 'refs/heads/main' && github.event_name == 'push' && github.ref != 'refs/heads/stable'
+    needs:
+      - Build-Release
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+      contents: read
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+
+      - name: Get body content
+        id: pr_body
+        run: |
+          echo "COMMITS_LIST<<EOF" >> $GITHUB_ENV
+          echo "### List of changements: " >> $GITHUB_ENV
+          git log origin/main..HEAD --oneline --pretty=format:"- %s (%h)" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+      - name: Create PR dev -> main
+        run: |
+          gh pr create \
+            --title "merge: ${{ github.ref_name }} -> main" \
+            --body "$COMMITS_LIST" \
+            --reviewer "copilot" \
+            --base main \
+            --head dev || echo "PR already exists or could not be created"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   GitHub-Release:
     if: startsWith(github.ref, 'refs/tags/v')
     needs: Build-Release
